/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewPlayerGUI;

import javax.swing.JFrame;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Mayur
 */
public class HomePage extends javax.swing.JFrame {
    public static String User_name;
    private EventList PresentEventList;
    private UserList ActivePlayerList = new UserList();
    private User ActivePlayer = null;
    private int ActivePlayerID = -1;

     public UserList getActivePlayerList() {
        return ActivePlayerList;
    }

    public User getActivePlayer() {
        return ActivePlayer;
    }

    public int getActivePlayerID() {
        return ActivePlayerID;
    }

    public void setActivePlayerList(UserList ActivePlayerList) {
        this.ActivePlayerList = ActivePlayerList;
    }

    public void setActivePlayer(User ActivePlayer) {
        this.ActivePlayer = ActivePlayer;
    }

    public void setActivePlayerID(int ActivePlayerID) {
        this.ActivePlayerID = ActivePlayerID;
    }
    
    /**
     * Creates new form HomePage
     * @param Uname
     * @throws java.io.IOException
     */
    public HomePage(String Uname) throws IOException {
        this.PresentEventList = new EventList();
        int localActivePlayerID = ActivePlayerList.getIDFromUsername(Uname);
        User localActivePlayer = ActivePlayerList.getUserFromID(localActivePlayerID);
        User_name = localActivePlayer.getUserFullName();   
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main_Screen = new javax.swing.JPanel();
        Username = new javax.swing.JLabel();
        Logout = new javax.swing.JButton();
        Options = new javax.swing.JTabbedPane();
        Events = new javax.swing.JTabbedPane();
        Calender = new javax.swing.JPanel();
        calenderList = new java.awt.List();
        Create = new javax.swing.JPanel();
        Create_Type = new javax.swing.JLabel();
        Create_type_ComboBox = new javax.swing.JComboBox<>();
        Create_Name = new javax.swing.JLabel();
        Create_Date = new javax.swing.JLabel();
        Create_Venue = new javax.swing.JLabel();
        Create_Member = new javax.swing.JLabel();
        Create_Name_text = new javax.swing.JTextField();
        Create_date_combobox = new javax.swing.JComboBox<>();
        Create_venue_txt = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        Create_Create = new javax.swing.JButton();
        Create_Cancel = new javax.swing.JButton();
        Schedule = new javax.swing.JPanel();
        Schedule_Type = new javax.swing.JLabel();
        Schedule_type_ComboBox = new javax.swing.JComboBox<>();
        Schedule_Name = new javax.swing.JLabel();
        Schedule_Date = new javax.swing.JLabel();
        Schedule_Venue = new javax.swing.JLabel();
        Schedule_Member = new javax.swing.JLabel();
        Schedule_date_combobox = new javax.swing.JComboBox<>();
        Schedule_venue_txt = new javax.swing.JTextField();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        Schedule_Cancel = new javax.swing.JButton();
        Schedule_Schedule = new javax.swing.JButton();
        Schedule_name_ComboBox = new javax.swing.JComboBox<>();
        Inventory = new javax.swing.JTabbedPane();
        Records = new javax.swing.JPanel();
        Record_Scrollpane = new javax.swing.JScrollPane();
        Record_List = new javax.swing.JList<>();
        Coachs_Request = new javax.swing.JPanel();
        Coach_Checkbox1 = new javax.swing.JCheckBox();
        Coach_Checkbox2 = new javax.swing.JCheckBox();
        Players_Request = new javax.swing.JPanel();
        Player_Checkbox1 = new javax.swing.JCheckBox();
        Player_Checkbox2 = new javax.swing.JCheckBox();
        Player_Checkbox3 = new javax.swing.JCheckBox();
        Members = new javax.swing.JTabbedPane();
        Players = new javax.swing.JScrollPane();
        Player_List = new javax.swing.JList<>();
        Coach = new javax.swing.JScrollPane();
        Coach_List = new javax.swing.JList<>();
        Management_Members = new javax.swing.JScrollPane();
        MM_List = new javax.swing.JList<>();
        Match_Score = new javax.swing.JTabbedPane();
        Welcome = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Main_Screen.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Main_Screen.setPreferredSize(new java.awt.Dimension(800, 600));

        Username.setText(User_name.toString());
        Username.setMaximumSize(new java.awt.Dimension(52, 100));
        Username.setMinimumSize(new java.awt.Dimension(52, 100));

        Logout.setText("Log Out");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        Options.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Options.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        Options.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Options.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        calenderList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calenderListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CalenderLayout = new javax.swing.GroupLayout(Calender);
        Calender.setLayout(CalenderLayout);
        CalenderLayout.setHorizontalGroup(
            CalenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(calenderList, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
        );
        CalenderLayout.setVerticalGroup(
            CalenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(calenderList, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
        );

        Events.addTab("Calender", Calender);

        Create_Type.setText("Type:");

        Create_type_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Meeting", "Practice", "Tryout", "Match" }));

        Create_Name.setText("Name:");

        Create_Date.setText("Date/ Time:");

        Create_Venue.setText("Venue:");

        Create_Member.setText("Members to be Present in Event:");

        Create_Name_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Create_Name_textActionPerformed(evt);
            }
        });

        Create_date_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Create_venue_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Create_venue_txtActionPerformed(evt);
            }
        });

        jCheckBox1.setText("Player 1");

        jCheckBox2.setText("Player 2");

        jCheckBox3.setText("Player 3");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        jCheckBox4.setText("Coach 1");

        jCheckBox5.setText("Coach 2");

        jCheckBox6.setText("Coach  3");

        jCheckBox7.setText("Management Member 1");

        jCheckBox8.setText("Management Member 2");

        jCheckBox9.setText("Management Member 3");

        Create_Create.setText("Create");
        Create_Create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Create_CreateActionPerformed(evt);
            }
        });

        Create_Cancel.setText("Cancel");

        javax.swing.GroupLayout CreateLayout = new javax.swing.GroupLayout(Create);
        Create.setLayout(CreateLayout);
        CreateLayout.setHorizontalGroup(
            CreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreateLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Create_Create)
                .addGap(18, 18, 18)
                .addComponent(Create_Cancel)
                .addContainerGap())
            .addGroup(CreateLayout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addGroup(CreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(CreateLayout.createSequentialGroup()
                            .addGroup(CreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Create_Type)
                                .addComponent(Create_Name))
                            .addGap(43, 43, 43)
                            .addGroup(CreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Create_Name_text, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Create_type_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(Create_Member)
                        .addGroup(CreateLayout.createSequentialGroup()
                            .addGroup(CreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Create_Date)
                                .addComponent(Create_Venue))
                            .addGap(18, 18, 18)
                            .addGroup(CreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Create_date_combobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Create_venue_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(CreateLayout.createSequentialGroup()
                        .addGroup(CreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CreateLayout.createSequentialGroup()
                                .addComponent(jCheckBox2)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox5))
                            .addGroup(CreateLayout.createSequentialGroup()
                                .addComponent(jCheckBox3)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox6))
                            .addGroup(CreateLayout.createSequentialGroup()
                                .addComponent(jCheckBox1)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox4)))
                        .addGap(18, 18, 18)
                        .addGroup(CreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox7)
                            .addComponent(jCheckBox9)
                            .addComponent(jCheckBox8))))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        CreateLayout.setVerticalGroup(
            CreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(CreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Create_type_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Create_Type, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Create_Name_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Create_Name))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Create_Date)
                    .addComponent(Create_date_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(CreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Create_Venue)
                    .addComponent(Create_venue_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Create_Member)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox4)
                    .addComponent(jCheckBox7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox5)
                    .addComponent(jCheckBox8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox6)
                    .addComponent(jCheckBox9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addGroup(CreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Create_Create)
                    .addComponent(Create_Cancel))
                .addContainerGap())
        );

        Events.addTab("Create", Create);

        Schedule_Type.setText("Type:");

        Schedule_type_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Meeting", "Practice", "Tryout", "Match" }));

        Schedule_Name.setText("Name:");

        Schedule_Date.setText("Date/ Time:");

        Schedule_Venue.setText("Venue:");

        Schedule_Member.setText("Members to be Present in Event:");

        Schedule_date_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jCheckBox10.setText("Player 1");

        jCheckBox11.setText("Player 2");

        jCheckBox12.setText("Player 3");
        jCheckBox12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox12ActionPerformed(evt);
            }
        });

        jCheckBox13.setText("Coach 1");

        jCheckBox14.setText("Coach 2");

        jCheckBox15.setText("Coach  3");

        jCheckBox16.setText("Management Member 1");

        jCheckBox17.setText("Management Member 2");

        jCheckBox18.setText("Management Member 3");

        Schedule_Cancel.setText("Cancel");
        Schedule_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Schedule_CancelActionPerformed(evt);
            }
        });

        Schedule_Schedule.setText("Schedule");

        Schedule_name_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Meeting for new Roster", "Tryout of Dilbert" }));

        javax.swing.GroupLayout ScheduleLayout = new javax.swing.GroupLayout(Schedule);
        Schedule.setLayout(ScheduleLayout);
        ScheduleLayout.setHorizontalGroup(
            ScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ScheduleLayout.createSequentialGroup()
                .addContainerGap(471, Short.MAX_VALUE)
                .addComponent(Schedule_Schedule)
                .addGap(18, 18, 18)
                .addComponent(Schedule_Cancel)
                .addContainerGap())
            .addGroup(ScheduleLayout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addGroup(ScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ScheduleLayout.createSequentialGroup()
                        .addGroup(ScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Schedule_Type)
                            .addComponent(Schedule_Name))
                        .addGap(43, 43, 43)
                        .addGroup(ScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Schedule_type_ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Schedule_name_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Schedule_Member)
                    .addGroup(ScheduleLayout.createSequentialGroup()
                        .addGroup(ScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Schedule_Date)
                            .addComponent(Schedule_Venue))
                        .addGap(18, 18, 18)
                        .addGroup(ScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Schedule_date_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Schedule_venue_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ScheduleLayout.createSequentialGroup()
                        .addGroup(ScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ScheduleLayout.createSequentialGroup()
                                .addComponent(jCheckBox11)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox14))
                            .addGroup(ScheduleLayout.createSequentialGroup()
                                .addComponent(jCheckBox12)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox15))
                            .addGroup(ScheduleLayout.createSequentialGroup()
                                .addComponent(jCheckBox10)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox13)))
                        .addGap(18, 18, 18)
                        .addGroup(ScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox16)
                            .addComponent(jCheckBox18)
                            .addComponent(jCheckBox17))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ScheduleLayout.setVerticalGroup(
            ScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ScheduleLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(ScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Schedule_type_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Schedule_Type, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Schedule_Name)
                    .addComponent(Schedule_name_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Schedule_Date)
                    .addComponent(Schedule_date_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(ScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Schedule_Venue)
                    .addComponent(Schedule_venue_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Schedule_Member)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox10)
                    .addComponent(jCheckBox13)
                    .addComponent(jCheckBox16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox11)
                    .addComponent(jCheckBox14)
                    .addComponent(jCheckBox17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox12)
                    .addComponent(jCheckBox15)
                    .addComponent(jCheckBox18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addGroup(ScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Schedule_Schedule)
                    .addComponent(Schedule_Cancel))
                .addContainerGap())
        );

        Events.addTab("Schedule", Schedule);

        Options.addTab("Events", Events);

        Record_List.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "1. 10 practice tools ", "2. 50 health drinks", "3. 5 broom " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        Record_Scrollpane.setViewportView(Record_List);

        javax.swing.GroupLayout RecordsLayout = new javax.swing.GroupLayout(Records);
        Records.setLayout(RecordsLayout);
        RecordsLayout.setHorizontalGroup(
            RecordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RecordsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Record_Scrollpane, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
                .addContainerGap())
        );
        RecordsLayout.setVerticalGroup(
            RecordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RecordsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Record_Scrollpane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(242, Short.MAX_VALUE))
        );

        Inventory.addTab("Records", Records);

        Coach_Checkbox1.setText("Request for Broom");
        Coach_Checkbox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Coach_Checkbox1ActionPerformed(evt);
            }
        });

        Coach_Checkbox2.setText("Energy Drink");
        Coach_Checkbox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Coach_Checkbox2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Coachs_RequestLayout = new javax.swing.GroupLayout(Coachs_Request);
        Coachs_Request.setLayout(Coachs_RequestLayout);
        Coachs_RequestLayout.setHorizontalGroup(
            Coachs_RequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Coachs_RequestLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(Coachs_RequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Coach_Checkbox2)
                    .addComponent(Coach_Checkbox1))
                .addContainerGap(493, Short.MAX_VALUE))
        );
        Coachs_RequestLayout.setVerticalGroup(
            Coachs_RequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Coachs_RequestLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(Coach_Checkbox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Coach_Checkbox2)
                .addContainerGap(315, Short.MAX_VALUE))
        );

        Inventory.addTab("Coach's Request", Coachs_Request);

        Player_Checkbox1.setText("Request for Broom");
        Player_Checkbox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Player_Checkbox1ActionPerformed(evt);
            }
        });

        Player_Checkbox2.setText("Energy Drink");
        Player_Checkbox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Player_Checkbox2ActionPerformed(evt);
            }
        });

        Player_Checkbox3.setText("New dresses");

        javax.swing.GroupLayout Players_RequestLayout = new javax.swing.GroupLayout(Players_Request);
        Players_Request.setLayout(Players_RequestLayout);
        Players_RequestLayout.setHorizontalGroup(
            Players_RequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Players_RequestLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(Players_RequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Player_Checkbox3)
                    .addComponent(Player_Checkbox2)
                    .addComponent(Player_Checkbox1))
                .addContainerGap(493, Short.MAX_VALUE))
        );
        Players_RequestLayout.setVerticalGroup(
            Players_RequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Players_RequestLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(Player_Checkbox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Player_Checkbox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Player_Checkbox3)
                .addContainerGap(289, Short.MAX_VALUE))
        );

        Inventory.addTab("Player's Request", Players_Request);

        Options.addTab("Inventory", Inventory);

        Player_List.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Player 1 - Team captain", "player 2", "player 3", "player 4", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        Players.setViewportView(Player_List);

        Members.addTab("Players", Players);

        Coach_List.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "coach 1- head coach", "coach 2", "coach 3" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        Coach.setViewportView(Coach_List);

        Members.addTab("Coach", Coach);

        MM_List.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Member 1", "Member 2", "member 3", "Member 4", "Member 5", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        Management_Members.setViewportView(MM_List);

        Members.addTab("Management Members", Management_Members);

        Options.addTab("Club members", Members);

        Match_Score.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        Options.addTab("Match Scores", Match_Score);

        Welcome.setFont(new java.awt.Font("Monotype Corsiva", 3, 18)); // NOI18N
        Welcome.setText("Quidditch Club");

        javax.swing.GroupLayout Main_ScreenLayout = new javax.swing.GroupLayout(Main_Screen);
        Main_Screen.setLayout(Main_ScreenLayout);
        Main_ScreenLayout.setHorizontalGroup(
            Main_ScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Main_ScreenLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(Welcome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Logout))
            .addComponent(Options, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        Main_ScreenLayout.setVerticalGroup(
            Main_ScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Main_ScreenLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(Main_ScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Welcome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Main_ScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Logout)
                        .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Options)
                .addContainerGap())
        );

        Options.getAccessibleContext().setAccessibleName("Inventory");

        getContentPane().add(Main_Screen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                
                new Login().setVisible(true);
                
            }
        });
        // TODO add your handling code here:
    }//GEN-LAST:event_LogoutActionPerformed

    private void Player_Checkbox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Player_Checkbox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Player_Checkbox1ActionPerformed

    private void Player_Checkbox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Player_Checkbox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Player_Checkbox2ActionPerformed

    private void Coach_Checkbox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Coach_Checkbox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Coach_Checkbox1ActionPerformed

    private void Coach_Checkbox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Coach_Checkbox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Coach_Checkbox2ActionPerformed

    private void Create_Name_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Create_Name_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Create_Name_textActionPerformed

    private void Create_CreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Create_CreateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Create_CreateActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox12ActionPerformed

    private void Schedule_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Schedule_CancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Schedule_CancelActionPerformed

    private void Create_venue_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Create_venue_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Create_venue_txtActionPerformed

    private void calenderListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calenderListActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_calenderListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
          

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new HomePage(User_name).setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Calender;
    private javax.swing.JScrollPane Coach;
    private javax.swing.JCheckBox Coach_Checkbox1;
    private javax.swing.JCheckBox Coach_Checkbox2;
    private javax.swing.JList<String> Coach_List;
    private javax.swing.JPanel Coachs_Request;
    private javax.swing.JPanel Create;
    private javax.swing.JButton Create_Cancel;
    private javax.swing.JButton Create_Create;
    private javax.swing.JLabel Create_Date;
    private javax.swing.JLabel Create_Member;
    private javax.swing.JLabel Create_Name;
    private javax.swing.JTextField Create_Name_text;
    private javax.swing.JLabel Create_Type;
    private javax.swing.JLabel Create_Venue;
    private javax.swing.JComboBox<String> Create_date_combobox;
    private javax.swing.JComboBox<String> Create_type_ComboBox;
    private javax.swing.JTextField Create_venue_txt;
    private javax.swing.JTabbedPane Events;
    private javax.swing.JTabbedPane Inventory;
    private javax.swing.JButton Logout;
    private javax.swing.JList<String> MM_List;
    private javax.swing.JPanel Main_Screen;
    private javax.swing.JScrollPane Management_Members;
    private javax.swing.JTabbedPane Match_Score;
    private javax.swing.JTabbedPane Members;
    private javax.swing.JTabbedPane Options;
    private javax.swing.JCheckBox Player_Checkbox1;
    private javax.swing.JCheckBox Player_Checkbox2;
    private javax.swing.JCheckBox Player_Checkbox3;
    private javax.swing.JList<String> Player_List;
    private javax.swing.JScrollPane Players;
    private javax.swing.JPanel Players_Request;
    private javax.swing.JList<String> Record_List;
    private javax.swing.JScrollPane Record_Scrollpane;
    private javax.swing.JPanel Records;
    private javax.swing.JPanel Schedule;
    private javax.swing.JButton Schedule_Cancel;
    private javax.swing.JLabel Schedule_Date;
    private javax.swing.JLabel Schedule_Member;
    private javax.swing.JLabel Schedule_Name;
    private javax.swing.JButton Schedule_Schedule;
    private javax.swing.JLabel Schedule_Type;
    private javax.swing.JLabel Schedule_Venue;
    private javax.swing.JComboBox<String> Schedule_date_combobox;
    private javax.swing.JComboBox<String> Schedule_name_ComboBox;
    private javax.swing.JComboBox<String> Schedule_type_ComboBox;
    private javax.swing.JTextField Schedule_venue_txt;
    private javax.swing.JLabel Username;
    private java.awt.Label Welcome;
    private java.awt.List calenderList;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    // End of variables declaration//GEN-END:variables
}
