package ViewPlayerGUI;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Brown Biggers
 */
public class QuidditchPlayerView extends javax.swing.JFrame{
    private UserList ActivePlayerList;
    private PlayerStatsList ActivePlayerStats;
    private User ActivePlayer;
    private int ActivePlayerID;
    
    public QuidditchPlayerView(UserList ActivePlayerList, PlayerStatsList ActivePlayerStats){
        this.ActivePlayerList = ActivePlayerList;
        this.ActivePlayerStats = ActivePlayerStats;
        this.ActivePlayer = null;
        this.ActivePlayerID = -1;
        initComponents();
//        puts frame in center of screen:
        this.setLocationRelativeTo(null);
    }
    
    /**
     * Creates new form QuidditchMain
     * 
     */
//    public QuidditchPlayerView(){
//        
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plrEventAttendGroup = new javax.swing.ButtonGroup();
        plrSubmitTeamRequest = new javax.swing.JDialog();
        plrSubmitTeamPrompt = new javax.swing.JLabel();
        plrSubmitTeamDrop = new javax.swing.JComboBox();
        plrSubmitTeamConfirm = new javax.swing.JButton();
        plrSubmitTeamCancel = new javax.swing.JButton();
        plrViewEditStats = new javax.swing.JDialog();
        statsEditPlayerLbl = new javax.swing.JLabel();
        statsEditPlayerFld = new javax.swing.JTextField();
        statsEditGameLbl = new javax.swing.JLabel();
        statsEditGameDrop = new javax.swing.JComboBox();
        statsEditQuafflePtsLbl = new javax.swing.JLabel();
        statsEditQuafflePtsFld = new javax.swing.JFormattedTextField();
        statsEditSnitchPtsLbl = new javax.swing.JLabel();
        statsEditSnitchPtsFld = new javax.swing.JFormattedTextField();
        statsEditFoulLbl = new javax.swing.JLabel();
        statsEditFoulFld = new javax.swing.JFormattedTextField();
        statsEditConfirm = new javax.swing.JButton();
        statsEditCancel = new javax.swing.JButton();
        plrSupplyRequest = new javax.swing.JDialog();
        plrSupplyRequestPrompt = new javax.swing.JLabel();
        plrSupplyRequestItemsFld = new javax.swing.JTextField();
        plrSupplyConfirmPrompt = new javax.swing.JLabel();
        plrSupplyConfirmYes = new javax.swing.JButton();
        plrSupplyConfirmNo = new javax.swing.JButton();
        plrMainDialog = new javax.swing.JFrame();
        plrInfoLogout = new javax.swing.JButton();
        plrNameLabel = new javax.swing.JLabel();
        plrNameTextField = new javax.swing.JTextField();
        plrTabPane = new javax.swing.JTabbedPane();
        plrTabEvents = new javax.swing.JPanel();
        plrEventScroll = new javax.swing.JScrollPane();
        plrEventScrollList = new javax.swing.JList<String>();
        plrEventDetailsPanel = new javax.swing.JPanel();
        plrEventDetailsName = new javax.swing.JLabel();
        plrEventDetailsNameField = new javax.swing.JTextField();
        plrEventDetailsDate = new javax.swing.JLabel();
        plrEventDetailsDateField = new javax.swing.JTextField();
        plrEventDetailsTime = new javax.swing.JLabel();
        plrEventDetailsTimeField = new javax.swing.JTextField();
        plrEventDetailsLoc = new javax.swing.JLabel();
        plrEventDetailsLocField = new javax.swing.JTextField();
        plrEventDetailsDesc = new javax.swing.JLabel();
        plrEventDetailsDescScroll = new javax.swing.JScrollPane();
        plrEventDetailsDescText = new javax.swing.JTextArea();
        plrEventDetailsAttend = new javax.swing.JLabel();
        plrEventAttendYes = new javax.swing.JRadioButton();
        plrEventAttendNo = new javax.swing.JRadioButton();
        plrEventStatsEdit = new javax.swing.JButton();
        plrTabTeams = new javax.swing.JPanel();
        plrTeamScroll = new javax.swing.JScrollPane();
        plrTeamScrollList = new javax.swing.JList<String>();
        plrTeamDetailsPanel = new javax.swing.JPanel();
        plrTeamDetailsBtrALbl = new javax.swing.JLabel();
        plrTeamDetailsBtrBLbl = new javax.swing.JLabel();
        plrTeamDetailsChsALbl = new javax.swing.JLabel();
        plrTeamDetailsChsBLbl = new javax.swing.JLabel();
        plrTeamDetailsChsCLbl = new javax.swing.JLabel();
        plrTeamDetailsKeepLbl = new javax.swing.JLabel();
        plrTeamDetailsSeekLbl = new javax.swing.JLabel();
        plrTeamDetailsCoachLbl = new javax.swing.JLabel();
        plrTeamDetailsBtrAFld = new javax.swing.JTextField();
        plrTeamDetailsChsAFld = new javax.swing.JTextField();
        plrTeamDetailsChsBFld = new javax.swing.JTextField();
        plrTeamDetailsChsCFld = new javax.swing.JTextField();
        plrTeamDetailsKeepFld = new javax.swing.JTextField();
        plrTeamDetailsSeekFld = new javax.swing.JTextField();
        plrTeamDetailsCoachFld = new javax.swing.JTextField();
        plrTeamDetailsBtrBFld = new javax.swing.JTextField();
        plrTeamRegister = new javax.swing.JButton();
        plrTabSupplies = new javax.swing.JPanel();
        plrSuppliesScroll = new javax.swing.JScrollPane();
        plrSuppliesScrollList = new javax.swing.JList<String>();
        plrSuppliesDetailsPanel = new javax.swing.JPanel();
        plrSupplyItemLbl = new javax.swing.JLabel();
        plrSupplyItemFld = new javax.swing.JTextField();
        plrSupplyDescLbl = new javax.swing.JLabel();
        plrSupplyDescFld = new javax.swing.JTextField();
        plrSupplyQuantityLbl = new javax.swing.JLabel();
        plrSupplyQuantityFld = new javax.swing.JSpinner();
        plrSupplyNotesLbl = new javax.swing.JLabel();
        plrSupplyNotesScroll = new javax.swing.JScrollPane();
        plrSupplyNotesText = new javax.swing.JTextArea();
        plrSupplyRequestButton = new javax.swing.JButton();
        plrInfoPanel = new javax.swing.JPanel();
        plrUpdatePlayerInfo = new javax.swing.JButton();
        plrErrorDialog = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        plrEditContactInfo = new javax.swing.JFrame();
        editLblHead = new javax.swing.JLabel();
        editLblUsername = new javax.swing.JLabel();
        editLblFName = new javax.swing.JLabel();
        editLblLName = new javax.swing.JLabel();
        editLblAdd1 = new javax.swing.JLabel();
        editLblAdd2 = new javax.swing.JLabel();
        editLblState = new javax.swing.JLabel();
        editLblZip = new javax.swing.JLabel();
        editLblEmail = new javax.swing.JLabel();
        editLblPhone = new javax.swing.JLabel();
        editLblGender = new javax.swing.JLabel();
        editContactUsername = new javax.swing.JTextField();
        editContactFirstName = new javax.swing.JTextField();
        editContactLastName = new javax.swing.JTextField();
        editContactAddressLine1 = new javax.swing.JTextField();
        editContactAddressLine2 = new javax.swing.JTextField();
        editContactCity = new javax.swing.JTextField();
        editContactState = new javax.swing.JTextField();
        editContactZip = new javax.swing.JTextField();
        editContactEmail = new javax.swing.JTextField();
        editContactPhoneNumber = new javax.swing.JTextField();
        editContactGender = new javax.swing.JTextField();
        editContactOk = new javax.swing.JButton();
        editContactCancel = new javax.swing.JButton();
        loginUserLabel = new javax.swing.JLabel();
        loginUserField = new javax.swing.JTextField();
        loginOkButton = new javax.swing.JButton();
        loginCancelButton = new javax.swing.JButton();

        plrSubmitTeamRequest.setTitle("Select a team:");
        plrSubmitTeamRequest.setLocation(new java.awt.Point(200, 200));
        plrSubmitTeamRequest.setResizable(false);
        plrSubmitTeamRequest.setSize(new java.awt.Dimension(550, 100));

        plrSubmitTeamPrompt.setText("Please choose a team to submit request:");

        plrSubmitTeamDrop.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cone Cobras", "Grogan Gorgons", "Guilford Gryffons", "Mary Foust Mongooses", "Moore-Strong More Strongs", "North Spencer Spiders", "Phillips-Hawkins Pangolins", "Ragsdale-Mendenhall Remainders", "Reynolds Rakshasas", "South Spencer Sidewinders", "Weil-Winfield Whale Sharks" }));

        plrSubmitTeamConfirm.setText("Confirm");
        plrSubmitTeamConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plrSubmitTeamConfirmActionPerformed(evt);
            }
        });

        plrSubmitTeamCancel.setText("Cancel");

        javax.swing.GroupLayout plrSubmitTeamRequestLayout = new javax.swing.GroupLayout(plrSubmitTeamRequest.getContentPane());
        plrSubmitTeamRequest.getContentPane().setLayout(plrSubmitTeamRequestLayout);
        plrSubmitTeamRequestLayout.setHorizontalGroup(
            plrSubmitTeamRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plrSubmitTeamRequestLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(plrSubmitTeamPrompt)
                .addGap(18, 18, 18)
                .addGroup(plrSubmitTeamRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(plrSubmitTeamRequestLayout.createSequentialGroup()
                        .addComponent(plrSubmitTeamConfirm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(plrSubmitTeamCancel))
                    .addComponent(plrSubmitTeamDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        plrSubmitTeamRequestLayout.setVerticalGroup(
            plrSubmitTeamRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plrSubmitTeamRequestLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(plrSubmitTeamRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plrSubmitTeamPrompt)
                    .addComponent(plrSubmitTeamDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(plrSubmitTeamRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plrSubmitTeamConfirm)
                    .addComponent(plrSubmitTeamCancel))
                .addGap(19, 19, 19))
        );

        plrViewEditStats.setTitle("Edit/View Player Statistics");
        plrViewEditStats.setLocation(new java.awt.Point(200, 200));
        plrViewEditStats.setResizable(false);
        plrViewEditStats.setSize(new java.awt.Dimension(475, 225));

        statsEditPlayerLbl.setText("Player:");

        statsEditPlayerFld.setEditable(false);
        statsEditPlayerFld.setText("Matt Smith");
        statsEditPlayerFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statsEditPlayerFldActionPerformed(evt);
            }
        });

        statsEditGameLbl.setText("Game:");

        statsEditGameDrop.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Game 1", "Game 2", "Game 3", "Game 4" }));
        statsEditGameDrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statsEditGameDropActionPerformed(evt);
            }
        });

        statsEditQuafflePtsLbl.setText("Quaffles:");

        statsEditQuafflePtsFld.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        statsEditQuafflePtsFld.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        statsEditQuafflePtsFld.setText("0");

        statsEditSnitchPtsLbl.setText("Snitch:");

        statsEditSnitchPtsFld.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        statsEditSnitchPtsFld.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        statsEditSnitchPtsFld.setText("0");

        statsEditFoulLbl.setText("Fouls:");

        statsEditFoulFld.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("hh:mm:ss"))));
        statsEditFoulFld.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        statsEditFoulFld.setText("0");
        statsEditFoulFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statsEditFoulFldActionPerformed(evt);
            }
        });

        statsEditConfirm.setText("Confirm");
        statsEditConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statsEditConfirmActionPerformed(evt);
            }
        });

        statsEditCancel.setText("Cancel");
        statsEditCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statsEditCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout plrViewEditStatsLayout = new javax.swing.GroupLayout(plrViewEditStats.getContentPane());
        plrViewEditStats.getContentPane().setLayout(plrViewEditStatsLayout);
        plrViewEditStatsLayout.setHorizontalGroup(
            plrViewEditStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plrViewEditStatsLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(plrViewEditStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statsEditQuafflePtsLbl)
                    .addComponent(statsEditGameLbl)
                    .addComponent(statsEditPlayerLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(plrViewEditStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statsEditGameDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(plrViewEditStatsLayout.createSequentialGroup()
                        .addComponent(statsEditQuafflePtsFld, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(statsEditSnitchPtsLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(statsEditSnitchPtsFld, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addGroup(plrViewEditStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(plrViewEditStatsLayout.createSequentialGroup()
                                .addComponent(statsEditConfirm)
                                .addGap(18, 18, 18)
                                .addComponent(statsEditCancel))
                            .addGroup(plrViewEditStatsLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(statsEditFoulLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(statsEditFoulFld, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(statsEditPlayerFld, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        plrViewEditStatsLayout.setVerticalGroup(
            plrViewEditStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plrViewEditStatsLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(plrViewEditStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statsEditPlayerLbl)
                    .addComponent(statsEditPlayerFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(plrViewEditStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statsEditGameLbl)
                    .addComponent(statsEditGameDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(plrViewEditStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statsEditQuafflePtsLbl)
                    .addComponent(statsEditQuafflePtsFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statsEditSnitchPtsLbl)
                    .addComponent(statsEditSnitchPtsFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statsEditFoulLbl)
                    .addComponent(statsEditFoulFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(plrViewEditStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statsEditConfirm)
                    .addComponent(statsEditCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        plrSupplyRequest.setTitle("Requesting Supplies");
        plrSupplyRequest.setLocation(new java.awt.Point(200, 200));
        plrSupplyRequest.setResizable(false);
        plrSupplyRequest.setSize(new java.awt.Dimension(475, 225));

        plrSupplyRequestPrompt.setText("You have requested the following supplies:");

        plrSupplyRequestItemsFld.setEditable(false);
        plrSupplyRequestItemsFld.setText("Snitch Harness");

        plrSupplyConfirmPrompt.setText("Is this correct?");

        plrSupplyConfirmYes.setText("Yes");

        plrSupplyConfirmNo.setText("No");

        javax.swing.GroupLayout plrSupplyRequestLayout = new javax.swing.GroupLayout(plrSupplyRequest.getContentPane());
        plrSupplyRequest.getContentPane().setLayout(plrSupplyRequestLayout);
        plrSupplyRequestLayout.setHorizontalGroup(
            plrSupplyRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plrSupplyRequestLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(plrSupplyRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(plrSupplyRequestLayout.createSequentialGroup()
                        .addGroup(plrSupplyRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(plrSupplyRequestItemsFld)
                            .addGroup(plrSupplyRequestLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(plrSupplyConfirmYes, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(plrSupplyConfirmNo, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20))
                    .addGroup(plrSupplyRequestLayout.createSequentialGroup()
                        .addGroup(plrSupplyRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(plrSupplyConfirmPrompt)
                            .addComponent(plrSupplyRequestPrompt))
                        .addContainerGap(162, Short.MAX_VALUE))))
        );
        plrSupplyRequestLayout.setVerticalGroup(
            plrSupplyRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plrSupplyRequestLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(plrSupplyRequestPrompt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(plrSupplyRequestItemsFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(plrSupplyConfirmPrompt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(plrSupplyRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plrSupplyConfirmYes)
                    .addComponent(plrSupplyConfirmNo))
                .addContainerGap())
        );

        plrMainDialog.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        plrMainDialog.setLocationByPlatform(true);
        plrMainDialog.setResizable(false);
        plrMainDialog.setSize(new java.awt.Dimension(818, 660));

        plrInfoLogout.setText("Logout");
        plrInfoLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plrInfoLogoutActionPerformed(evt);
            }
        });

        plrNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        plrNameLabel.setText("Player Name:");
        plrNameLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        plrNameLabel.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        plrNameTextField.setEditable(false);
        plrNameTextField.setText("Matt Smith");
        plrNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plrNameTextFieldActionPerformed(evt);
            }
        });

        plrEventScrollList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Game 1", "Game 2", "Game 3", "Game 4", "Game 5", "Game 6", "Game 7", "Game 8", "Game 9", "Game 10", "Game 11", "Game 12", "Game 13", "Game 14", "Game 15", "Game 16", "Game 17", "Game 18", "Game 19", "Game 20", "Game 21", "Game 22", "Game 23", "Game 24", "Game 25", "Game 26", "Game 27", "Game 28", "Game 29", "Game 30", "Game 31", "Game 32", "Game 33" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        plrEventScroll.setViewportView(plrEventScrollList);

        plrEventDetailsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Event Details"));
        plrEventDetailsPanel.setFocusable(false);

        plrEventDetailsName.setText("Event:");

        plrEventDetailsNameField.setEditable(false);
        plrEventDetailsNameField.setText("Game 2: Minneapolis Accio Snowball");

        plrEventDetailsDate.setText("Date:");

        plrEventDetailsDateField.setEditable(false);
        plrEventDetailsDateField.setText("November 27, 2016");

        plrEventDetailsTime.setText("Time:");

        plrEventDetailsTimeField.setEditable(false);
        plrEventDetailsTimeField.setText("7:00 PM");

        plrEventDetailsLoc.setText("Location:");

        plrEventDetailsLocField.setEditable(false);
        plrEventDetailsLocField.setText("UNCG Quidditch Pitch");

        plrEventDetailsDesc.setText("Description:");

        plrEventDetailsDescText.setEditable(false);
        plrEventDetailsDescText.setColumns(20);
        plrEventDetailsDescText.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        plrEventDetailsDescText.setLineWrap(true);
        plrEventDetailsDescText.setRows(5);
        plrEventDetailsDescText.setText("This is our last preseason game against an out-of-state opponent. After this, the regular season starts, and our schedule is set until May. Game starts at 8:00 PM, and we will meet at the UNCG Quidditch Pitch at 7:00 PM for a pregame meeting.");
        plrEventDetailsDescText.setWrapStyleWord(true);
        plrEventDetailsDescScroll.setViewportView(plrEventDetailsDescText);

        plrEventDetailsAttend.setText("Attending:");

        plrEventAttendYes.setText("Yes");

        plrEventAttendNo.setText("No");

        plrEventStatsEdit.setText("Edit Statistics...");
        plrEventStatsEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plrEventStatsEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout plrEventDetailsPanelLayout = new javax.swing.GroupLayout(plrEventDetailsPanel);
        plrEventDetailsPanel.setLayout(plrEventDetailsPanelLayout);
        plrEventDetailsPanelLayout.setHorizontalGroup(
            plrEventDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plrEventDetailsPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(plrEventDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(plrEventDetailsPanelLayout.createSequentialGroup()
                        .addGroup(plrEventDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(plrEventDetailsPanelLayout.createSequentialGroup()
                                .addGroup(plrEventDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(plrEventDetailsName)
                                    .addComponent(plrEventDetailsDate)
                                    .addComponent(plrEventDetailsTime)
                                    .addComponent(plrEventDetailsLoc))
                                .addGap(13, 13, 13))
                            .addComponent(plrEventDetailsDesc, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(plrEventDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(plrEventDetailsPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(plrEventAttendYes)
                                .addGap(18, 18, 18)
                                .addComponent(plrEventAttendNo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(plrEventStatsEdit))
                            .addGroup(plrEventDetailsPanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(plrEventDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(plrEventDetailsDescScroll, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(plrEventDetailsDateField)
                                    .addComponent(plrEventDetailsNameField)
                                    .addComponent(plrEventDetailsTimeField)
                                    .addComponent(plrEventDetailsLocField)))))
                    .addGroup(plrEventDetailsPanelLayout.createSequentialGroup()
                        .addComponent(plrEventDetailsAttend)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        plrEventDetailsPanelLayout.setVerticalGroup(
            plrEventDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plrEventDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(plrEventDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plrEventDetailsName)
                    .addComponent(plrEventDetailsNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(plrEventDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plrEventDetailsDate)
                    .addComponent(plrEventDetailsDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(plrEventDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plrEventDetailsTime)
                    .addComponent(plrEventDetailsTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(plrEventDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plrEventDetailsLoc)
                    .addComponent(plrEventDetailsLocField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(plrEventDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(plrEventDetailsPanelLayout.createSequentialGroup()
                        .addComponent(plrEventDetailsDesc)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(plrEventDetailsDescScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(plrEventDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plrEventDetailsAttend)
                    .addComponent(plrEventAttendYes)
                    .addComponent(plrEventAttendNo)
                    .addComponent(plrEventStatsEdit))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout plrTabEventsLayout = new javax.swing.GroupLayout(plrTabEvents);
        plrTabEvents.setLayout(plrTabEventsLayout);
        plrTabEventsLayout.setHorizontalGroup(
            plrTabEventsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plrTabEventsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(plrTabEventsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(plrTabEventsLayout.createSequentialGroup()
                        .addComponent(plrEventScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addComponent(plrEventDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        plrTabEventsLayout.setVerticalGroup(
            plrTabEventsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plrTabEventsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(plrEventScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(plrEventDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        plrTabPane.addTab("Events", plrTabEvents);

        plrTeamScrollList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Cone Cobras", "Grogan Gorgons", "Guilford Gryffons", "Mary Foust Mongooses", "Moore-Strong More Strongs", "North Spencer Spiders", "Phillips-Hawkins Pangolins", "Ragsdale-Mendenhall Remainders", "Reynolds Rakshasas", "South Spencer Sidewinders", "Weil-Winfield Whale Sharks" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        plrTeamScroll.setViewportView(plrTeamScrollList);

        plrTeamDetailsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Team Details"));
        plrTeamDetailsPanel.setFocusable(false);

        plrTeamDetailsBtrALbl.setText("Beater:");

        plrTeamDetailsBtrBLbl.setText("Beater:");

        plrTeamDetailsChsALbl.setText("Chaser:");

        plrTeamDetailsChsBLbl.setText("Chaser:");

        plrTeamDetailsChsCLbl.setText("Chaser:");

        plrTeamDetailsKeepLbl.setText("Keeper:");

        plrTeamDetailsSeekLbl.setText("Seeker:");

        plrTeamDetailsCoachLbl.setText("Coach:");

        plrTeamDetailsBtrAFld.setEditable(false);
        plrTeamDetailsBtrAFld.setText("William Hartnell");

        plrTeamDetailsChsAFld.setEditable(false);
        plrTeamDetailsChsAFld.setText("Jon Pertwee");

        plrTeamDetailsChsBFld.setEditable(false);
        plrTeamDetailsChsBFld.setText("Tom Baker");

        plrTeamDetailsChsCFld.setEditable(false);
        plrTeamDetailsChsCFld.setText("Peter Davison");

        plrTeamDetailsKeepFld.setEditable(false);
        plrTeamDetailsKeepFld.setText("Colin Baker");

        plrTeamDetailsSeekFld.setEditable(false);
        plrTeamDetailsSeekFld.setText("Sylvester McCoy");

        plrTeamDetailsCoachFld.setEditable(false);
        plrTeamDetailsCoachFld.setText("Paul McGann");

        plrTeamDetailsBtrBFld.setEditable(false);
        plrTeamDetailsBtrBFld.setText("Patrick Troughton");

        plrTeamRegister.setText("Register for team...");
        plrTeamRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plrTeamRegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout plrTeamDetailsPanelLayout = new javax.swing.GroupLayout(plrTeamDetailsPanel);
        plrTeamDetailsPanel.setLayout(plrTeamDetailsPanelLayout);
        plrTeamDetailsPanelLayout.setHorizontalGroup(
            plrTeamDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plrTeamDetailsPanelLayout.createSequentialGroup()
                .addGroup(plrTeamDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(plrTeamDetailsPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(plrTeamDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(plrTeamDetailsBtrALbl)
                            .addComponent(plrTeamDetailsBtrBLbl)
                            .addComponent(plrTeamDetailsChsALbl)
                            .addComponent(plrTeamDetailsChsBLbl)
                            .addComponent(plrTeamDetailsChsCLbl)
                            .addComponent(plrTeamDetailsKeepLbl)
                            .addComponent(plrTeamDetailsSeekLbl)
                            .addComponent(plrTeamDetailsCoachLbl))
                        .addGap(29, 29, 29)
                        .addGroup(plrTeamDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(plrTeamDetailsBtrAFld)
                            .addComponent(plrTeamDetailsBtrBFld, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                            .addComponent(plrTeamDetailsChsAFld)
                            .addComponent(plrTeamDetailsChsBFld)
                            .addComponent(plrTeamDetailsChsCFld)
                            .addComponent(plrTeamDetailsKeepFld)
                            .addComponent(plrTeamDetailsSeekFld)
                            .addComponent(plrTeamDetailsCoachFld)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, plrTeamDetailsPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(plrTeamRegister)))
                .addContainerGap())
        );
        plrTeamDetailsPanelLayout.setVerticalGroup(
            plrTeamDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plrTeamDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(plrTeamDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plrTeamDetailsBtrALbl)
                    .addComponent(plrTeamDetailsBtrAFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(plrTeamDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plrTeamDetailsBtrBFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plrTeamDetailsBtrBLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(plrTeamDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plrTeamDetailsChsAFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plrTeamDetailsChsALbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(plrTeamDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plrTeamDetailsChsBFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plrTeamDetailsChsBLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(plrTeamDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plrTeamDetailsChsCLbl)
                    .addComponent(plrTeamDetailsChsCFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(plrTeamDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plrTeamDetailsKeepLbl)
                    .addComponent(plrTeamDetailsKeepFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(plrTeamDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plrTeamDetailsSeekLbl)
                    .addComponent(plrTeamDetailsSeekFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(plrTeamDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plrTeamDetailsCoachLbl)
                    .addComponent(plrTeamDetailsCoachFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(plrTeamRegister)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout plrTabTeamsLayout = new javax.swing.GroupLayout(plrTabTeams);
        plrTabTeams.setLayout(plrTabTeamsLayout);
        plrTabTeamsLayout.setHorizontalGroup(
            plrTabTeamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plrTabTeamsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(plrTabTeamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(plrTeamScroll)
                    .addComponent(plrTeamDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        plrTabTeamsLayout.setVerticalGroup(
            plrTabTeamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plrTabTeamsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(plrTeamScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(plrTeamDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        plrTabPane.addTab("Teams", plrTabTeams);

        plrSuppliesScrollList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Bludger", "Broom - SM", "Broom - MD", "Broom - LG", "Headband (Snitch)", "Headband (Beater)", "Headband (Keeper)", "Headband (Seeker)", "Headband (Chaser)", "Hoop", "Quaffle", "Snitch", "Snitch Harness" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        plrSuppliesScroll.setViewportView(plrSuppliesScrollList);

        plrSuppliesDetailsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Supplies/Equipment"));
        plrSuppliesDetailsPanel.setFocusable(false);

        plrSupplyItemLbl.setText("Item:");

        plrSupplyItemFld.setEditable(false);
        plrSupplyItemFld.setText("Snitch Harness");

        plrSupplyDescLbl.setText("Desc:");

        plrSupplyDescFld.setEditable(false);
        plrSupplyDescFld.setText("Harness for player as the snitch. Official equipment for tournament play.");

        plrSupplyQuantityLbl.setText("Quantity:");

        plrSupplyNotesLbl.setText("Notes");

        plrSupplyNotesText.setColumns(20);
        plrSupplyNotesText.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        plrSupplyNotesText.setLineWrap(true);
        plrSupplyNotesText.setRows(5);
        plrSupplyNotesText.setText("I think our snitch is broken. Part of the fabric is missing, and it may change game play. We need a new one before Game 2, as we're hosting the event.");
        plrSupplyNotesText.setWrapStyleWord(true);
        plrSupplyNotesScroll.setViewportView(plrSupplyNotesText);

        plrSupplyRequestButton.setText("Request Supplies...");
        plrSupplyRequestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plrSupplyRequestButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout plrSuppliesDetailsPanelLayout = new javax.swing.GroupLayout(plrSuppliesDetailsPanel);
        plrSuppliesDetailsPanel.setLayout(plrSuppliesDetailsPanelLayout);
        plrSuppliesDetailsPanelLayout.setHorizontalGroup(
            plrSuppliesDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plrSuppliesDetailsPanelLayout.createSequentialGroup()
                .addGroup(plrSuppliesDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(plrSuppliesDetailsPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(plrSuppliesDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(plrSupplyItemLbl)
                            .addComponent(plrSupplyDescLbl)
                            .addComponent(plrSupplyQuantityLbl)
                            .addComponent(plrSupplyNotesLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(plrSuppliesDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(plrSupplyDescFld, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                            .addComponent(plrSupplyItemFld, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(plrSupplyNotesScroll)
                            .addComponent(plrSupplyQuantityFld, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, plrSuppliesDetailsPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(plrSupplyRequestButton)))
                .addContainerGap())
        );
        plrSuppliesDetailsPanelLayout.setVerticalGroup(
            plrSuppliesDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plrSuppliesDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(plrSuppliesDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plrSupplyItemLbl)
                    .addComponent(plrSupplyItemFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(plrSuppliesDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plrSupplyDescFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plrSupplyDescLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(plrSuppliesDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plrSupplyQuantityLbl)
                    .addComponent(plrSupplyQuantityFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(plrSuppliesDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(plrSupplyNotesLbl)
                    .addComponent(plrSupplyNotesScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(plrSupplyRequestButton)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout plrTabSuppliesLayout = new javax.swing.GroupLayout(plrTabSupplies);
        plrTabSupplies.setLayout(plrTabSuppliesLayout);
        plrTabSuppliesLayout.setHorizontalGroup(
            plrTabSuppliesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plrTabSuppliesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(plrTabSuppliesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(plrTabSuppliesLayout.createSequentialGroup()
                        .addComponent(plrSuppliesScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addComponent(plrSuppliesDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        plrTabSuppliesLayout.setVerticalGroup(
            plrTabSuppliesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plrTabSuppliesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(plrSuppliesScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(plrSuppliesDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        plrTabPane.addTab("Supplies", plrTabSupplies);

        plrInfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Player Information"));

        javax.swing.GroupLayout plrInfoPanelLayout = new javax.swing.GroupLayout(plrInfoPanel);
        plrInfoPanel.setLayout(plrInfoPanelLayout);
        plrInfoPanelLayout.setHorizontalGroup(
            plrInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 225, Short.MAX_VALUE)
        );
        plrInfoPanelLayout.setVerticalGroup(
            plrInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        plrUpdatePlayerInfo.setText("Edit Contact...");
        plrUpdatePlayerInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plrUpdatePlayerInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout plrMainDialogLayout = new javax.swing.GroupLayout(plrMainDialog.getContentPane());
        plrMainDialog.getContentPane().setLayout(plrMainDialogLayout);
        plrMainDialogLayout.setHorizontalGroup(
            plrMainDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plrMainDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(plrMainDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(plrMainDialogLayout.createSequentialGroup()
                        .addComponent(plrNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(plrNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(plrMainDialogLayout.createSequentialGroup()
                        .addGroup(plrMainDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(plrMainDialogLayout.createSequentialGroup()
                                .addComponent(plrUpdatePlayerInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(plrInfoLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(plrInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plrTabPane)
                .addContainerGap())
        );
        plrMainDialogLayout.setVerticalGroup(
            plrMainDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, plrMainDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(plrMainDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(plrTabPane, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(plrMainDialogLayout.createSequentialGroup()
                        .addGroup(plrMainDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(plrNameTextField)
                            .addComponent(plrNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(63, 63, 63)
                        .addGroup(plrMainDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(plrInfoLogout)
                            .addComponent(plrUpdatePlayerInfo))
                        .addGap(24, 24, 24)
                        .addComponent(plrInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout plrErrorDialogLayout = new javax.swing.GroupLayout(plrErrorDialog.getContentPane());
        plrErrorDialog.getContentPane().setLayout(plrErrorDialogLayout);
        plrErrorDialogLayout.setHorizontalGroup(
            plrErrorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plrErrorDialogLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jLabel1)
                .addContainerGap(268, Short.MAX_VALUE))
        );
        plrErrorDialogLayout.setVerticalGroup(
            plrErrorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plrErrorDialogLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel1)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        plrEditContactInfo.setResizable(false);
        plrEditContactInfo.setSize(new java.awt.Dimension(350, 450));

        editLblHead.setText("Edit Player Contact Info:");

        editLblUsername.setText("Username:");

        editLblFName.setText("First Name:");

        editLblLName.setText("Last Name:");

        editLblAdd1.setText("Address:");

        editLblAdd2.setText("City:");

        editLblState.setText("State:");

        editLblZip.setText("Zip:");

        editLblEmail.setText("Email:");

        editLblPhone.setText("Phone:");

        editLblGender.setText("Gender:");

        editContactUsername.setEditable(false);
        editContactUsername.setText("jTextField1");

        editContactFirstName.setText("jTextField2");

        editContactLastName.setText("jTextField3");

        editContactAddressLine1.setText("jTextField4");

        editContactAddressLine2.setText("jTextField5");

        editContactCity.setText("jTextField6");

        editContactState.setText("jTextField7");

        editContactZip.setText("jTextField8");

        editContactEmail.setText("jTextField9");

        editContactPhoneNumber.setText("jTextField10");

        editContactGender.setText("jTextField1");

        editContactOk.setText("Ok");
        editContactOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editContactOkActionPerformed(evt);
            }
        });

        editContactCancel.setText("Cancel");
        editContactCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editContactCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout plrEditContactInfoLayout = new javax.swing.GroupLayout(plrEditContactInfo.getContentPane());
        plrEditContactInfo.getContentPane().setLayout(plrEditContactInfoLayout);
        plrEditContactInfoLayout.setHorizontalGroup(
            plrEditContactInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, plrEditContactInfoLayout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addComponent(editContactOk, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editContactCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(plrEditContactInfoLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(plrEditContactInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(editLblHead)
                    .addGroup(plrEditContactInfoLayout.createSequentialGroup()
                        .addGroup(plrEditContactInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editLblFName)
                            .addComponent(editLblUsername))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(plrEditContactInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(editContactUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(editContactFirstName)))
                    .addGroup(plrEditContactInfoLayout.createSequentialGroup()
                        .addGroup(plrEditContactInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editLblLName)
                            .addComponent(editLblAdd1)
                            .addComponent(editLblAdd2)
                            .addComponent(editLblState)
                            .addComponent(editLblZip)
                            .addComponent(editLblEmail)
                            .addComponent(editLblPhone)
                            .addComponent(editLblGender, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(plrEditContactInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editContactGender)
                            .addComponent(editContactLastName)
                            .addComponent(editContactAddressLine1)
                            .addComponent(editContactAddressLine2)
                            .addComponent(editContactCity)
                            .addComponent(editContactState)
                            .addComponent(editContactZip)
                            .addComponent(editContactEmail)
                            .addComponent(editContactPhoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        plrEditContactInfoLayout.setVerticalGroup(
            plrEditContactInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plrEditContactInfoLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(editLblHead)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(plrEditContactInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editLblUsername)
                    .addComponent(editContactUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(plrEditContactInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editLblFName)
                    .addComponent(editContactFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(plrEditContactInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editLblLName)
                    .addComponent(editContactLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(plrEditContactInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editLblAdd1)
                    .addComponent(editContactAddressLine1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editContactAddressLine2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(plrEditContactInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editLblAdd2)
                    .addComponent(editContactCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(plrEditContactInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editLblState)
                    .addComponent(editContactState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(plrEditContactInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editLblZip)
                    .addComponent(editContactZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(plrEditContactInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editLblEmail)
                    .addComponent(editContactEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(plrEditContactInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editLblPhone)
                    .addComponent(editContactPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(plrEditContactInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editLblGender)
                    .addComponent(editContactGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(plrEditContactInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editContactOk)
                    .addComponent(editContactCancel))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("loginScreen"); // NOI18N
        setResizable(false);

        loginUserLabel.setText("user name:");

        loginUserField.setText("enter your username...");
        loginUserField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginUserFieldMouseClicked(evt);
            }
        });

        loginOkButton.setText("ok");
        loginOkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginOkButtonActionPerformed(evt);
            }
        });

        loginCancelButton.setText("cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(loginUserLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loginUserField, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(loginOkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(loginCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginUserLabel)
                    .addComponent(loginUserField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginOkButton)
                    .addComponent(loginCancelButton))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginOkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginOkButtonActionPerformed
        // TODO add your handling code here:
        
        String inputUserName = loginUserField.getText().toLowerCase();
        if (this.ActivePlayerList.getIDFromUsername(inputUserName) > -1) {
            this.ActivePlayerID = this.ActivePlayerList.getIDFromUsername(inputUserName);
            this.ActivePlayer = this.ActivePlayerList.getUserFromID(ActivePlayerID);
            plrMainDialog.setVisible(true);
            plrMainDialog.setLocationRelativeTo(null);
            plrNameTextField.setText(this.ActivePlayer.getUserFullName());
            this.dispose();
        }
        else{
//            display error dialog...
            JOptionPane.showMessageDialog(this, "Please enter a valid username.");
        }
        
    }//GEN-LAST:event_loginOkButtonActionPerformed

    private void loginUserFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginUserFieldMouseClicked
        loginUserField.setText("");
    }//GEN-LAST:event_loginUserFieldMouseClicked

    private void plrSubmitTeamConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plrSubmitTeamConfirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plrSubmitTeamConfirmActionPerformed

    private void statsEditFoulFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statsEditFoulFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statsEditFoulFldActionPerformed

    private void plrInfoLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plrInfoLogoutActionPerformed
        // This is the button that will probably become a logout action
    }//GEN-LAST:event_plrInfoLogoutActionPerformed

    private void plrNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plrNameTextFieldActionPerformed
        // Since this is a text field, it may be editable. Otherwise, might be just locked from edits outside of account creation.
    }//GEN-LAST:event_plrNameTextFieldActionPerformed

    private void plrTeamRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plrTeamRegisterActionPerformed
        plrSubmitTeamRequest.setVisible(true);
    }//GEN-LAST:event_plrTeamRegisterActionPerformed

    private void plrSupplyRequestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plrSupplyRequestButtonActionPerformed
        plrSupplyRequest.setVisible(true);
    }//GEN-LAST:event_plrSupplyRequestButtonActionPerformed

    private void plrUpdatePlayerInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plrUpdatePlayerInfoActionPerformed
        plrEditContactInfo.setVisible(true);
        plrEditContactInfo.setLocationRelativeTo(null);
        editContactUsername.setText(ActivePlayer.getUserName());
        editContactFirstName.setText(ActivePlayer.getUserFirstName());
        editContactLastName.setText(ActivePlayer.getUserLastName());
        editContactAddressLine1.setText(ActivePlayer.getUserAddressLine1());
        editContactAddressLine2.setText(ActivePlayer.getUserAddressLine2());
        editContactCity.setText(ActivePlayer.getUserCity());
        editContactState.setText(ActivePlayer.getUserState());
        editContactZip.setText(ActivePlayer.getUserZip());
        editContactEmail.setText(ActivePlayer.getUserEmail());
        editContactPhoneNumber.setText(ActivePlayer.getUserPhoneNumber());
        editContactGender.setText(ActivePlayer.getUserGender());
    }//GEN-LAST:event_plrUpdatePlayerInfoActionPerformed

    private void plrEventStatsEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plrEventStatsEditActionPerformed
        plrViewEditStats.setVisible(true);
        plrViewEditStats.setLocationRelativeTo(null);
        statsEditPlayerFld.setText(ActivePlayer.getUserFullName());
        statsEditGameDrop.setModel(new DefaultComboBoxModel(ActivePlayerStats.getPlayerEvents(ActivePlayerID).toArray()));
        Object selectedEvent = statsEditGameDrop.getSelectedItem();
        
        if(selectedEvent != null){
            int selectedEventInt = Integer.parseInt(selectedEvent.toString());
            int[] playerEventStats = ActivePlayerStats.getPlayerEventStats(ActivePlayerID,selectedEventInt);
            statsEditQuafflePtsFld.setText(String.valueOf(playerEventStats[2]));
            statsEditSnitchPtsFld.setText(String.valueOf(playerEventStats[3]));
            statsEditFoulFld.setText(String.valueOf(playerEventStats[4]));
        }
        
    }//GEN-LAST:event_plrEventStatsEditActionPerformed

    private void editContactCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editContactCancelActionPerformed
         plrEditContactInfo.setVisible(false);
    }//GEN-LAST:event_editContactCancelActionPerformed

    private void editContactOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editContactOkActionPerformed
        
        ActivePlayer.setUserName(editContactUsername.getText());
        ActivePlayer.setUserFirstName(editContactFirstName.getText());
        ActivePlayer.setUserLastName(editContactLastName.getText());
        ActivePlayer.setUserAddressLine1(editContactAddressLine1.getText());
        ActivePlayer.setUserAddressLine2(editContactAddressLine2.getText());
        ActivePlayer.setUserCity(editContactCity.getText());
        ActivePlayer.setUserState(editContactState.getText());
        ActivePlayer.setUserZip(editContactZip.getText());
        ActivePlayer.setUserEmail(editContactEmail.getText());
        ActivePlayer.setUserPhoneNumber(editContactPhoneNumber.getText());
        ActivePlayer.setUserGender(editContactGender.getText());
        try {
            ActivePlayerList.writeListToCSV();
        } catch (IOException ex) {
            Logger.getLogger(QuidditchPlayerView.class.getName()).log(Level.SEVERE, null, ex);
        }
        plrEditContactInfo.setVisible(false);
    }//GEN-LAST:event_editContactOkActionPerformed

    private void statsEditPlayerFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statsEditPlayerFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statsEditPlayerFldActionPerformed

    private void statsEditGameDropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statsEditGameDropActionPerformed
        Object selectedEvent = statsEditGameDrop.getSelectedItem();
        
        if(selectedEvent != null){
            int selectedEventInt = Integer.parseInt(selectedEvent.toString());
            int[] playerEventStats = ActivePlayerStats.getPlayerEventStats(ActivePlayerID,selectedEventInt);
            statsEditQuafflePtsFld.setText(String.valueOf(playerEventStats[2]));
            statsEditSnitchPtsFld.setText(String.valueOf(playerEventStats[3]));
            statsEditFoulFld.setText(String.valueOf(playerEventStats[4]));
        }
    }//GEN-LAST:event_statsEditGameDropActionPerformed

    private void statsEditCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statsEditCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statsEditCancelActionPerformed

    private void statsEditConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statsEditConfirmActionPerformed
        
        
//        ActivePlayerStats.setPlayerEventStats();
    }//GEN-LAST:event_statsEditConfirmActionPerformed

    /**
     * @param args the command line arguments
     * @throws java.io.IOException
     */
    public static void main(String args[]) throws IOException {
        UserList initPlayerList = new UserList();
        PlayerStatsList initPlayerStats = new PlayerStatsList();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new QuidditchPlayerView(initPlayerList, initPlayerStats).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField editContactAddressLine1;
    private javax.swing.JTextField editContactAddressLine2;
    private javax.swing.JButton editContactCancel;
    private javax.swing.JTextField editContactCity;
    private javax.swing.JTextField editContactEmail;
    private javax.swing.JTextField editContactFirstName;
    private javax.swing.JTextField editContactGender;
    private javax.swing.JTextField editContactLastName;
    private javax.swing.JButton editContactOk;
    private javax.swing.JTextField editContactPhoneNumber;
    private javax.swing.JTextField editContactState;
    private javax.swing.JTextField editContactUsername;
    private javax.swing.JTextField editContactZip;
    private javax.swing.JLabel editLblAdd1;
    private javax.swing.JLabel editLblAdd2;
    private javax.swing.JLabel editLblEmail;
    private javax.swing.JLabel editLblFName;
    private javax.swing.JLabel editLblGender;
    private javax.swing.JLabel editLblHead;
    private javax.swing.JLabel editLblLName;
    private javax.swing.JLabel editLblPhone;
    private javax.swing.JLabel editLblState;
    private javax.swing.JLabel editLblUsername;
    private javax.swing.JLabel editLblZip;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton loginCancelButton;
    private javax.swing.JButton loginOkButton;
    private javax.swing.JTextField loginUserField;
    private javax.swing.JLabel loginUserLabel;
    private javax.swing.JFrame plrEditContactInfo;
    private javax.swing.JDialog plrErrorDialog;
    private javax.swing.ButtonGroup plrEventAttendGroup;
    private javax.swing.JRadioButton plrEventAttendNo;
    private javax.swing.JRadioButton plrEventAttendYes;
    private javax.swing.JLabel plrEventDetailsAttend;
    private javax.swing.JLabel plrEventDetailsDate;
    private javax.swing.JTextField plrEventDetailsDateField;
    private javax.swing.JLabel plrEventDetailsDesc;
    private javax.swing.JScrollPane plrEventDetailsDescScroll;
    private javax.swing.JTextArea plrEventDetailsDescText;
    private javax.swing.JLabel plrEventDetailsLoc;
    private javax.swing.JTextField plrEventDetailsLocField;
    private javax.swing.JLabel plrEventDetailsName;
    private javax.swing.JTextField plrEventDetailsNameField;
    private javax.swing.JPanel plrEventDetailsPanel;
    private javax.swing.JLabel plrEventDetailsTime;
    private javax.swing.JTextField plrEventDetailsTimeField;
    private javax.swing.JScrollPane plrEventScroll;
    private javax.swing.JList<String> plrEventScrollList;
    private javax.swing.JButton plrEventStatsEdit;
    private javax.swing.JButton plrInfoLogout;
    private javax.swing.JPanel plrInfoPanel;
    private javax.swing.JFrame plrMainDialog;
    private javax.swing.JLabel plrNameLabel;
    private javax.swing.JTextField plrNameTextField;
    private javax.swing.JButton plrSubmitTeamCancel;
    private javax.swing.JButton plrSubmitTeamConfirm;
    private javax.swing.JComboBox plrSubmitTeamDrop;
    private javax.swing.JLabel plrSubmitTeamPrompt;
    private javax.swing.JDialog plrSubmitTeamRequest;
    private javax.swing.JPanel plrSuppliesDetailsPanel;
    private javax.swing.JScrollPane plrSuppliesScroll;
    private javax.swing.JList<String> plrSuppliesScrollList;
    private javax.swing.JButton plrSupplyConfirmNo;
    private javax.swing.JLabel plrSupplyConfirmPrompt;
    private javax.swing.JButton plrSupplyConfirmYes;
    private javax.swing.JTextField plrSupplyDescFld;
    private javax.swing.JLabel plrSupplyDescLbl;
    private javax.swing.JTextField plrSupplyItemFld;
    private javax.swing.JLabel plrSupplyItemLbl;
    private javax.swing.JLabel plrSupplyNotesLbl;
    private javax.swing.JScrollPane plrSupplyNotesScroll;
    private javax.swing.JTextArea plrSupplyNotesText;
    private javax.swing.JSpinner plrSupplyQuantityFld;
    private javax.swing.JLabel plrSupplyQuantityLbl;
    private javax.swing.JDialog plrSupplyRequest;
    private javax.swing.JButton plrSupplyRequestButton;
    private javax.swing.JTextField plrSupplyRequestItemsFld;
    private javax.swing.JLabel plrSupplyRequestPrompt;
    private javax.swing.JPanel plrTabEvents;
    private javax.swing.JTabbedPane plrTabPane;
    private javax.swing.JPanel plrTabSupplies;
    private javax.swing.JPanel plrTabTeams;
    private javax.swing.JTextField plrTeamDetailsBtrAFld;
    private javax.swing.JLabel plrTeamDetailsBtrALbl;
    private javax.swing.JTextField plrTeamDetailsBtrBFld;
    private javax.swing.JLabel plrTeamDetailsBtrBLbl;
    private javax.swing.JTextField plrTeamDetailsChsAFld;
    private javax.swing.JLabel plrTeamDetailsChsALbl;
    private javax.swing.JTextField plrTeamDetailsChsBFld;
    private javax.swing.JLabel plrTeamDetailsChsBLbl;
    private javax.swing.JTextField plrTeamDetailsChsCFld;
    private javax.swing.JLabel plrTeamDetailsChsCLbl;
    private javax.swing.JTextField plrTeamDetailsCoachFld;
    private javax.swing.JLabel plrTeamDetailsCoachLbl;
    private javax.swing.JTextField plrTeamDetailsKeepFld;
    private javax.swing.JLabel plrTeamDetailsKeepLbl;
    private javax.swing.JPanel plrTeamDetailsPanel;
    private javax.swing.JTextField plrTeamDetailsSeekFld;
    private javax.swing.JLabel plrTeamDetailsSeekLbl;
    private javax.swing.JButton plrTeamRegister;
    private javax.swing.JScrollPane plrTeamScroll;
    private javax.swing.JList<String> plrTeamScrollList;
    private javax.swing.JButton plrUpdatePlayerInfo;
    private javax.swing.JDialog plrViewEditStats;
    private javax.swing.JButton statsEditCancel;
    private javax.swing.JButton statsEditConfirm;
    private javax.swing.JFormattedTextField statsEditFoulFld;
    private javax.swing.JLabel statsEditFoulLbl;
    private javax.swing.JComboBox statsEditGameDrop;
    private javax.swing.JLabel statsEditGameLbl;
    private javax.swing.JTextField statsEditPlayerFld;
    private javax.swing.JLabel statsEditPlayerLbl;
    private javax.swing.JFormattedTextField statsEditQuafflePtsFld;
    private javax.swing.JLabel statsEditQuafflePtsLbl;
    private javax.swing.JFormattedTextField statsEditSnitchPtsFld;
    private javax.swing.JLabel statsEditSnitchPtsLbl;
    // End of variables declaration//GEN-END:variables
}
